# Connection Details
$env:SHARED_ACCESS_KEY_NAME = "iothubowner"
$env:DEVICE_NAME = ""
$env:IOTHUB_DEVICE_CONN_STRING = ""
$env:IOTHUB_CONN_STRING_CSHARP = ""
$env:SERVICE_CONNECTION_STRING = ""
$env:EVENT_HUBS_COMPATIBILITY_ENDPOINT = ""
$env:EVENT_HUBS_COMPATIBILITY_PATH = ""
$env:EVENT_HUBS_SAS_KEY = ""
$env:EVENT_HUBS_CONNECTION_STRING = ""

